/* eslint-disable */
/* tslint:disable */
/**
 * ---------------------------------------------------------------
 * ## THIS FILE WAS AUTO-GENERATED BY generate-api-wrapper.js  ##
 * ## DO NOT EDIT MANUALLY                                      ##
 * ---------------------------------------------------------------
 *
 * This wrapper automatically unwraps Pin framework response format:
 * - Success: { data: T, trace_id: string } -> T
 * - Error: { error: string, ... } -> throws ApiError
 */

import { Api as GeneratedApi } from './api.js'

/**
 * Pin framework response format
 */
export interface PinResponse<T> {
  data: T
  trace_id?: string
}

/**
 * Pin framework error response format
 */
export interface PinErrorResponse {
  error: {
    message: string
    type?: string
    key?: string
  }
  trace_id?: string
}

/**
 * Custom API Error class
 */
export class ApiError extends Error {
  constructor(
    message: string,
    public readonly key?: string,
    public readonly meta?: Record<string, any>,
    public readonly status?: string,
    public readonly traceId?: string,
    public readonly statusCode?: number
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

/**
 * Unwrap Pin response data field
 */
function unwrapData<T>(promise: Promise<PinResponse<T>>): Promise<T> {
  return promise
    .then(response => {
      const responseData = response as any
      if (responseData.data?.error) {
        throw new ApiError(
          responseData.data.error.message,
          responseData.data.error.key,
          undefined,
          responseData.data.error.type,
          responseData.data.trace_id
        )
      }
      return responseData.data
    })
    .catch(error => {
      if (error instanceof ApiError) throw error
      if (error.response) {
        const errorData = error.response.data
        throw new ApiError(
          errorData?.error?.message || error.message || 'Unknown error',
          errorData?.error?.key,
          undefined,
          errorData?.error?.type,
          errorData?.trace_id,
          error.response.status
        )
      }
      throw new ApiError(error.message || 'Network error')
    })
}

type UnwrapPinResponse<T> = T extends { data?: infer R } ? UnwrapPinResponse<R> : T

/**
 * Wrapped API type that returns unwrapped data
 */
type UnwrappedApi = {
  [K in keyof GeneratedApi<unknown>]: GeneratedApi<unknown>[K] extends (...args: infer Args) => Promise<infer R>
    ? (...args: Args) => Promise<UnwrapPinResponse<R>>
    : GeneratedApi<unknown>[K] extends object
    ? UnwrapNamespace<GeneratedApi<unknown>[K]>
    : GeneratedApi<unknown>[K]
}

type UnwrapNamespace<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => Promise<infer R>
    ? (...args: Args) => Promise<UnwrapPinResponse<R>>
    : T[K]
}

/**
 * Create wrapped API instance
 */
export function createApi(config: ConstructorParameters<typeof GeneratedApi<any>>[0]): UnwrappedApi {
  const rawApi = new GeneratedApi<any>(config)
  const wrappedApi: any = {}
  
  wrappedApi.api = {}
  for (const key in rawApi.api) {
    const method = (rawApi.api as any)[key]
    if (typeof method === 'function') {
      wrappedApi.api[key] = (...args: any[]) => unwrapData(method.apply(rawApi.api, args))
    }
  }
  
  wrappedApi.authDomainLogin = {}
  for (const key in rawApi.authDomainLogin) {
    const method = (rawApi.authDomainLogin as any)[key]
    if (typeof method === 'function') {
      wrappedApi.authDomainLogin[key] = (...args: any[]) => unwrapData(method.apply(rawApi.authDomainLogin, args))
    }
  }
  
  wrappedApi.tenantAdmin = {}
  for (const key in rawApi.tenantAdmin) {
    const method = (rawApi.tenantAdmin as any)[key]
    if (typeof method === 'function') {
      wrappedApi.tenantAdmin[key] = (...args: any[]) => unwrapData(method.apply(rawApi.tenantAdmin, args))
    }
  }
  return wrappedApi as UnwrappedApi
}

export * from './api.js'
