/* eslint-disable */
/* tslint:disable */
/**
 * ---------------------------------------------------------------
 * ## THIS FILE WAS AUTO-GENERATED BY generate-api-wrapper.js  ##
 * ## DO NOT EDIT MANUALLY                                      ##
 * ---------------------------------------------------------------
 *
 * This wrapper automatically unwraps Pin framework response format:
 * - Success: { data: T, trace_id: string } -> T
 * - Error: { error: string, ... } -> throws ApiError
 */

import { Api as GeneratedApi } from './api.js'

/**
 * Pin framework response format
 */
export interface PinResponse<T> {
  data: T
  trace_id?: string
}

/**
 * Pin framework error response format
 */
export interface PinErrorResponse {
  error: {
    code?: string
    message: string
    type?: string
    key?: string
    requestId?: string
  }
  trace_id?: string
}

/**
 * Custom API Error class
 */
export class ApiError extends Error {
  constructor(
    message: string,
    public readonly key?: string,
    public readonly meta?: Record<string, any>,
    public readonly status?: string,
    public readonly traceId?: string,
    public readonly statusCode?: number,
    public readonly body?: unknown
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

function isPinErrorResponse(value: any): value is PinErrorResponse {
  return !!value && typeof value === 'object' && !!value.error && typeof value.error.message === 'string'
}

function extractPinErrorPayload(error: any): { body: PinErrorResponse; statusCode?: number } | null {
  if (isPinErrorResponse(error)) {
    return { body: error, statusCode: typeof error?.status === 'number' ? error.status : undefined }
  }
  if (isPinErrorResponse(error?.error)) {
    return { body: error.error, statusCode: typeof error?.status === 'number' ? error.status : undefined }
  }
  if (isPinErrorResponse(error?.response?.data)) {
    return { body: error.response.data, statusCode: error.response.status }
  }
  return null
}

/**
 * Unwrap Pin response data field
 */
function unwrapData<T>(promise: Promise<PinResponse<T>>): Promise<T> {
  return promise
    .then(response => {
      const responseData = response as any
      if (responseData.data?.error) {
        throw new ApiError(
          responseData.data.error.message,
          responseData.data.error.key,
          undefined,
          responseData.data.error.type,
          responseData.data.trace_id,
          undefined,
          responseData.data
        )
      }
      return responseData.data
    })
    .catch(error => {
      if (error instanceof ApiError) throw error
      const payload = extractPinErrorPayload(error)
      if (payload) {
        const errorData = payload.body
        throw new ApiError(
          errorData?.error?.message || error.message || 'Unknown error',
          errorData?.error?.key,
          undefined,
          errorData?.error?.type,
          errorData?.trace_id,
          payload.statusCode,
          errorData
        )
      }
      throw new ApiError(error.message || 'Network error')
    })
}

type UnwrapPinResponse<T> = T extends { data?: infer R } ? UnwrapPinResponse<R> : T

/**
 * Wrapped API type that returns unwrapped data
 */
type UnwrappedApi = {
  [K in keyof GeneratedApi<unknown>]: GeneratedApi<unknown>[K] extends (...args: infer Args) => Promise<infer R>
    ? (...args: Args) => Promise<UnwrapPinResponse<R>>
    : GeneratedApi<unknown>[K] extends object
    ? UnwrapNamespace<GeneratedApi<unknown>[K]>
    : GeneratedApi<unknown>[K]
}

type UnwrapNamespace<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => Promise<infer R>
    ? (...args: Args) => Promise<UnwrapPinResponse<R>>
    : T[K]
}

/**
 * Create wrapped API instance
 */
export function createApi(config: ConstructorParameters<typeof GeneratedApi<any>>[0]): UnwrappedApi {
  const rawApi = new GeneratedApi<any>(config)
  const wrappedApi: any = {}
  
  wrappedApi.admin = {}
  for (const key in rawApi.admin) {
    const method = (rawApi.admin as any)[key]
    if (typeof method === 'function') {
      wrappedApi.admin[key] = (...args: any[]) => unwrapData(method.apply(rawApi.admin, args))
    }
  }
  
  wrappedApi.api = {}
  for (const key in rawApi.api) {
    const method = (rawApi.api as any)[key]
    if (typeof method === 'function') {
      wrappedApi.api[key] = (...args: any[]) => unwrapData(method.apply(rawApi.api, args))
    }
  }
  
  wrappedApi.e2E = {}
  for (const key in rawApi.e2E) {
    const method = (rawApi.e2E as any)[key]
    if (typeof method === 'function') {
      wrappedApi.e2E[key] = (...args: any[]) => unwrapData(method.apply(rawApi.e2E, args))
    }
  }
  
  wrappedApi.tenantAdmin = {}
  for (const key in rawApi.tenantAdmin) {
    const method = (rawApi.tenantAdmin as any)[key]
    if (typeof method === 'function') {
      wrappedApi.tenantAdmin[key] = (...args: any[]) => unwrapData(method.apply(rawApi.tenantAdmin, args))
    }
  }
  return wrappedApi as UnwrappedApi
}

export * from './api.js'
