/* eslint-disable */
/* tslint:disable */
/**
 * ---------------------------------------------------------------
 * ## THIS FILE WAS AUTO-GENERATED BY generate-api-wrapper.js  ##
 * ## DO NOT EDIT MANUALLY                                      ##
 * ---------------------------------------------------------------
 *
 * This wrapper automatically unwraps Pin framework response format:
 * - Success: { data: T, trace_id: string } -> T
 * - Error: { error: string, ... } -> throws ApiError
 */

import { Api as GeneratedApi } from './api.js'

/**
 * Pin framework response format
 */
export interface PinResponse<T> {
  data: T
  trace_id?: string
}

/**
 * Pin framework error response format
 */
export interface PinErrorResponse {
  error: {
    code?: string
    message: string
    type?: string
    key?: string
    requestId?: string
  }
  trace_id?: string
}

/**
 * Custom API Error class
 */
export class ApiError extends Error {
  constructor(
    message: string,
    public readonly key?: string,
    public readonly meta?: Record<string, any>,
    public readonly status?: string,
    public readonly traceId?: string,
    public readonly statusCode?: number,
    public readonly body?: unknown,
    public readonly cause?: unknown
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

export class ApiUnavailableError extends ApiError {
  constructor(
    message: string,
    statusCode?: number,
    body?: unknown,
    cause?: unknown
  ) {
    super(message, undefined, undefined, 'unavailable', undefined, statusCode, body, cause)
    this.name = 'ApiUnavailableError'
  }
}

export function isApiUnavailableError(error: unknown): error is ApiUnavailableError {
  return error instanceof ApiUnavailableError || (
    !!error &&
    typeof error === 'object' &&
    (error as { name?: unknown }).name === 'ApiUnavailableError'
  )
}

function isPinErrorResponse(value: any): value is PinErrorResponse {
  return !!value && typeof value === 'object' && !!value.error && typeof value.error.message === 'string'
}

function extractPinErrorPayload(error: any): { body: PinErrorResponse; statusCode?: number } | null {
  if (isPinErrorResponse(error)) {
    return { body: error, statusCode: readHttpStatusCode(error) }
  }
  if (isPinErrorResponse(error?.error)) {
    return { body: error.error, statusCode: readHttpStatusCode(error) }
  }
  if (isPinErrorResponse(error?.response?.data)) {
    return { body: error.response.data, statusCode: error.response.status }
  }
  return null
}

function readHttpStatusCode(error: any): number | undefined {
  const candidates = [
    error?.statusCode,
    error?.status,
    error?.response?.status,
  ]
  for (const candidate of candidates) {
    if (typeof candidate === 'number' && Number.isFinite(candidate)) return candidate
    if (typeof candidate === 'string' && candidate.trim()) {
      const parsed = Number(candidate)
      if (Number.isFinite(parsed)) return parsed
    }
  }
  return undefined
}

function isUnavailableStatusCode(statusCode: number | undefined): boolean {
  return statusCode === 0 || (typeof statusCode === 'number' && statusCode >= 500)
}

function errorMessage(error: any, fallback: string): string {
  if (typeof error?.message === 'string' && error.message.trim()) return error.message
  if (typeof error?.statusText === 'string' && error.statusText.trim()) return error.statusText
  return fallback
}

function readErrorBody(error: any): unknown {
  return error?.body ?? error?.error ?? error?.response?.data
}

/**
 * Unwrap Pin response data field
 */
function unwrapData<T>(promise: Promise<PinResponse<T>>): Promise<T> {
  return promise
    .then(response => {
      const httpResponse = response as any
      const pinPayload = httpResponse?.data
      if (pinPayload?.error) {
        throw new ApiError(
          pinPayload.error.message,
          pinPayload.error.key,
          undefined,
          pinPayload.error.type,
          pinPayload.trace_id,
          undefined,
          pinPayload
        )
      }
      return pinPayload?.data ?? pinPayload
    })
    .catch(error => {
      if (error instanceof ApiError) throw error
      const payload = extractPinErrorPayload(error)
      if (payload) {
        const errorData = payload.body
        if (isUnavailableStatusCode(payload.statusCode)) {
          throw new ApiUnavailableError(
            errorData?.error?.message || errorMessage(error, 'Backend unavailable'),
            payload.statusCode,
            errorData,
            error
          )
        }
        throw new ApiError(
          errorData?.error?.message || errorMessage(error, 'Unknown error'),
          errorData?.error?.key,
          undefined,
          errorData?.error?.type,
          errorData?.trace_id,
          payload.statusCode,
          errorData,
          error
        )
      }
      const statusCode = readHttpStatusCode(error)
      if (isUnavailableStatusCode(statusCode) || statusCode == null) {
        throw new ApiUnavailableError(
          errorMessage(error, 'Backend unavailable'),
          statusCode,
          readErrorBody(error),
          error
        )
      }
      throw new ApiError(
        errorMessage(error, 'Unknown error'),
        undefined,
        undefined,
        undefined,
        undefined,
        statusCode,
        readErrorBody(error),
        error
      )
    })
}

type UnwrapPinResponse<T> = T extends { data?: infer R } ? UnwrapPinResponse<R> : T

/**
 * Wrapped API type that returns unwrapped data
 */
type UnwrappedApi = {
  [K in keyof GeneratedApi<unknown>]: GeneratedApi<unknown>[K] extends (...args: infer Args) => Promise<infer R>
    ? (...args: Args) => Promise<UnwrapPinResponse<R>>
    : GeneratedApi<unknown>[K] extends object
    ? UnwrapNamespace<GeneratedApi<unknown>[K]>
    : GeneratedApi<unknown>[K]
}

type UnwrapNamespace<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => Promise<infer R>
    ? (...args: Args) => Promise<UnwrapPinResponse<R>>
    : T[K]
}

/**
 * Create wrapped API instance
 */
export function createApi(config: ConstructorParameters<typeof GeneratedApi<any>>[0]): UnwrappedApi {
  const rawApi = new GeneratedApi<any>(config)
  const wrappedApi: any = {}
  
  wrappedApi.admin = {}
  for (const key in rawApi.admin) {
    const method = (rawApi.admin as any)[key]
    if (typeof method === 'function') {
      wrappedApi.admin[key] = (...args: any[]) => unwrapData(method.apply(rawApi.admin, args))
    }
  }
  
  wrappedApi.api = {}
  for (const key in rawApi.api) {
    const method = (rawApi.api as any)[key]
    if (typeof method === 'function') {
      wrappedApi.api[key] = (...args: any[]) => unwrapData(method.apply(rawApi.api, args))
    }
  }
  
  wrappedApi.e2E = {}
  for (const key in rawApi.e2E) {
    const method = (rawApi.e2E as any)[key]
    if (typeof method === 'function') {
      wrappedApi.e2E[key] = (...args: any[]) => unwrapData(method.apply(rawApi.e2E, args))
    }
  }
  
  wrappedApi.open = {}
  for (const key in rawApi.open) {
    const method = (rawApi.open as any)[key]
    if (typeof method === 'function') {
      wrappedApi.open[key] = (...args: any[]) => unwrapData(method.apply(rawApi.open, args))
    }
  }
  
  wrappedApi.tenantAdmin = {}
  for (const key in rawApi.tenantAdmin) {
    const method = (rawApi.tenantAdmin as any)[key]
    if (typeof method === 'function') {
      wrappedApi.tenantAdmin[key] = (...args: any[]) => unwrapData(method.apply(rawApi.tenantAdmin, args))
    }
  }
  return wrappedApi as UnwrappedApi
}

export * from './api.js'
