/* eslint-disable */
/* tslint:disable */
/**
 * ---------------------------------------------------------------
 * ## THIS FILE WAS AUTO-GENERATED BY generate-api-wrapper.js  ##
 * ## DO NOT EDIT MANUALLY                                      ##
 * ---------------------------------------------------------------
 */

import { Api as GeneratedApi } from './api.js'

type WrappedApi = GeneratedApi<unknown>

export function createApi(config: ConstructorParameters<typeof GeneratedApi<any>>[0]): WrappedApi {
  return new GeneratedApi<any>(config) as WrappedApi
}

export * from './api.js'
